name: push-notification

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            exit 1
          fi

      - name: âœ… Check for FIREBASE_API_KEY
        run: |
          if [ -z "${{ secrets.FIREBASE_API_KEY }}" ]; then
            exit 1
          fi

      - name: ğŸ— Setup repository
        uses: actions/checkout@v4

      - name: ğŸ›  Setup Environment
        id: env
        run: |-
          echo "EXPO_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env.local

      - name: ğŸ›  Setup google-services.json
        run: |-
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_SERVICES_GPG_KEY }}" --output google-services.json google-services.json.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_SERVICES_GPG_KEY }}

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸ“¡ Send push
        run: yarn --non-interactive -s node sendPushToEveryOne.js
        env:
          EXPO_ACCESS_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
