name: update
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            exit 1
          fi

      - name: âœ… Check for FIREBASE_API_KEY
        run: |
          if [ -z "${{ secrets.FIREBASE_API_KEY }}" ]; then
            exit 1
          fi

      - name: ğŸ— Setup repository
        uses: actions/checkout@v4

      - name: ğŸ›  Setup Environment
        id: env
        run: |-
          echo "EXPO_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env.local

      - name: ğŸ›  Setup google-services.json
        run: |-
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_SERVICES_GPG_KEY }}" --output google-services.json google-services.json.gpg

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸš€ Publish update
        run: eas update --auto

  build:
    name: EAS Build

    needs: [update]

    strategy:
      matrix:
        platform: ["android", "ios"] # ["android", "ios"] for iOS builds

    runs-on: ${{ matrix.platform == 'android' && 'ubuntu-latest' || 'macos-latest' }}

    steps:

      - name: ğŸ— Setup repository
        uses: actions/checkout@v4

      - name: ğŸ›  Setup Environment
        id: env
        run: |-
          echo "EAS_LOCAL_BUILD_ARTIFACTS_DIR=${{ runner.temp }}/eas-output" >> $GITHUB_ENV
          echo "EXPO_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env.local

      - name: ğŸ›  Setup google-services.json
        run: |-
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GOOGLE_SERVICES_GPG_KEY }}" --output google-services.json google-services.json.gpg
          echo "GOOGLE_SERVICES_FILE=$(pwd)/google-services.json" >> $GITHUB_ENV
          file="$(pwd)/google-services.json"
          sed -i -e "s%_GOOGLE_SERVICES_FILE_%$file%g" eas.json

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸ› ï¸ Prepare native build directories
        run: yarn expo prebuild --platform ${{ matrix.platform }}

      - name: ğŸ— Setup Java
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: ğŸ› ï¸ Build on EAS
        run: ${{ format('eas build --platform {0} --non-interactive --no-wait  --profile preview --local {1}',  matrix.platform, matrix.platform == 'ios' && '|| true' || '' ) }}

      - name: ğŸš€ Upload ${{ matrix.platform }} bundle
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }} bundle
          path: |
            ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}
